"use client";
import { PointerEvent,useEffect,useRef,useState } from "react";
type Area={id:number;name:string};type Item={id:number;x:number;y:number;width:number;height:number;shape:string;rotation:number;z_index?:number;number?:string;capacity?:number;area?:string;area_id?:number|null;active?:number;object_type?:string;label?:string};type Selected={kind:"table"|"object";id:number}|null;
const objectTypes=["wall","door","bar","pillar","tv","fixed_table","area","label"];
export default function TableLayoutPage(){const [tables,setTables]=useState<Item[]>([]),[objects,setObjects]=useState<Item[]>([]),[areas,setAreas]=useState<Area[]>([]),[width,setWidth]=useState(1200),[height,setHeight]=useState(760),[selected,setSelected]=useState<Selected>(null),[zoom,setZoom]=useState(.75),[loading,setLoading]=useState(true),[error,setError]=useState(""),[notice,setNotice]=useState("");const drag=useRef<{kind:"table"|"object";id:number;startX:number;startY:number;x:number;y:number}|null>(null);
 useEffect(()=>{let active=true;fetch("/api/booking/layout",{credentials:"include"}).then(r=>{if(!r.ok)throw new Error();return r.json()}).then(data=>{if(active){setTables(data.tables);setObjects(data.objects);setAreas(data.areas);setWidth(data.settings.canvas_width);setHeight(data.settings.canvas_height)}}).catch(()=>{if(active)setError("The layout could not be loaded. Manager access is required.")}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[]);
 const selectedItem=selected?(selected.kind==="table"?tables:objects).find(i=>i.id===selected.id):undefined;
 function update(kind:"table"|"object",id:number,change:Partial<Item>){const setter=kind==="table"?setTables:setObjects;setter(current=>current.map(item=>item.id===id?{...item,...change}:item))}
 function pointerDown(e:PointerEvent<HTMLDivElement>,kind:"table"|"object",item:Item){e.currentTarget.setPointerCapture(e.pointerId);drag.current={kind,id:item.id,startX:e.clientX,startY:e.clientY,x:item.x,y:item.y};setSelected({kind,id:item.id})}
 function pointerMove(e:PointerEvent<HTMLDivElement>){const current=drag.current;if(!current)return;update(current.kind,current.id,{x:Math.round(current.x+(e.clientX-current.startX)/zoom),y:Math.round(current.y+(e.clientY-current.startY)/zoom)})}
 function pointerUp(){drag.current=null}
 async function save(){setError("");const payload={canvasWidth:width,canvasHeight:height,tables:tables.map(i=>({...i,zIndex:0})),objects:objects.map(i=>({...i,zIndex:i.z_index||0}))};const r=await fetch("/api/booking/layout",{method:"PUT",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});if(!r.ok){setError("The layout could not be saved.");return}setNotice("Floor plan saved.")}
 async function addObject(type:string){const r=await fetch("/api/booking/layout/objects",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({objectType:type})}),data=await r.json().catch(()=>({}));if(!r.ok){setError(data.detail||"The object could not be added.");return}setObjects(current=>[...current,data.object]);setSelected({kind:"object",id:data.object.id});setNotice(`${type.replace("_"," ")} added.`)}
 async function saveObjectDetails(){if(!selected||selected.kind!=="object"||!selectedItem)return;const r=await fetch(`/api/booking/layout/objects/${selected.id}`,{method:"PUT",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({label:selectedItem.label,areaId:selectedItem.area_id})});if(!r.ok){setError("The object details could not be saved.");return}setNotice("Object details updated.")}
 async function duplicateObject(){if(!selected||selected.kind!=="object")return;const r=await fetch(`/api/booking/layout/objects/${selected.id}/duplicate`,{method:"POST",credentials:"include"}),data=await r.json().catch(()=>({}));if(!r.ok){setError(data.detail||"The object could not be duplicated.");return}setObjects(current=>[...current,data.object]);setSelected({kind:"object",id:data.object.id});setNotice("Object duplicated.")}
 async function removeObject(){if(!selected||selected.kind!=="object"||!selectedItem||!confirm(`Remove ${selectedItem.label}?`))return;const r=await fetch(`/api/booking/layout/objects/${selected.id}`,{method:"DELETE",credentials:"include"});if(!r.ok){setError("The object could not be removed.");return}setObjects(current=>current.filter(item=>item.id!==selected.id));setSelected(null);setNotice("Object removed.")}
 if(loading)return <main className="booking-main"><section className="booking-page"><div className="booking-empty">Loading floor plan...</div></section></main>;
 return <main className="booking-main"><section className="booking-page layout-editor-page"><header className="booking-heading"><div><span className="booking-page-kicker">Manager tools</span><h1>Table Layout Editor</h1><p>Drag tables and structural objects to match the pub floor plan.</p></div><button className="primary-button" onClick={save}>Save layout</button></header>{error&&<p className="booking-alert">{error}</p>}{notice&&<p className="booking-notice">{notice}</p>}
 <div className="layout-editor-toolbar"><div><strong>Add object</strong>{objectTypes.map(type=><button key={type} onClick={()=>addObject(type)}>{type.replace("_"," ")}</button>)}</div><div><strong>Map</strong><label>Width <input type="number" min="600" max="3000" value={width} onChange={e=>setWidth(Number(e.target.value))}/></label><label>Height <input type="number" min="400" max="2200" value={height} onChange={e=>setHeight(Number(e.target.value))}/></label></div><div><strong>Zoom</strong><button onClick={()=>setZoom(v=>Math.max(.3,v-.1))}>−</button><span>{Math.round(zoom*100)}%</span><button onClick={()=>setZoom(v=>Math.min(1.5,v+.1))}>+</button></div></div>
 <div className="layout-editor-workspace"><div className="layout-canvas-scroll"><div className="layout-canvas-scale" style={{width:width*zoom,height:height*zoom}}><div className="layout-canvas" style={{width,height,transform:`scale(${zoom})`}} onPointerMove={pointerMove} onPointerUp={pointerUp} onPointerCancel={pointerUp}>{objects.map(item=><div key={`o-${item.id}`} onPointerDown={e=>pointerDown(e,"object",item)} className={`visual-floor-object object-${item.object_type} shape-${item.shape} ${selected?.kind==="object"&&selected.id===item.id?"selected":""}`} style={{left:item.x,top:item.y,width:item.width,height:item.height,transform:`rotate(${item.rotation}deg)`,zIndex:item.z_index}}><span>{item.label}</span></div>)}{tables.map(item=><div key={`t-${item.id}`} onPointerDown={e=>pointerDown(e,"table",item)} className={`visual-layout-table shape-${item.shape} ${item.active?"":"inactive"} ${selected?.kind==="table"&&selected.id===item.id?"selected":""}`} style={{left:item.x,top:item.y,width:item.width,height:item.height,transform:`rotate(${item.rotation}deg)`}}><strong>T{item.number}</strong><span>{item.capacity} seats</span><small>{item.area}</small></div>)}</div></div></div>
 <aside className="layout-inspector"><h2>Selected item</h2>{!selectedItem?<p>Select a table or object on the map.</p>:<><strong>{selected?.kind==="table"?`Table ${selectedItem.number}`:selectedItem.label||"Unlabelled object"}</strong>{selected?.kind==="object"&&<><label>Label<input value={selectedItem.label||""} onChange={e=>update("object",selectedItem.id,{label:e.target.value})}/></label><label>Linked area<select value={selectedItem.area_id||""} onChange={e=>update("object",selectedItem.id,{area_id:e.target.value?Number(e.target.value):null})}><option value="">No area</option>{areas.map(a=><option value={a.id} key={a.id}>{a.name}</option>)}</select></label></>}<label>Shape<select value={selectedItem.shape} onChange={e=>update(selected!.kind,selectedItem.id,{shape:e.target.value})}>{["rectangle","square","round","oval"].map(v=><option key={v}>{v}</option>)}</select></label><label>Width<input type="number" value={Math.round(selectedItem.width)} onChange={e=>update(selected!.kind,selectedItem.id,{width:Number(e.target.value)})}/></label><label>Height<input type="number" value={Math.round(selectedItem.height)} onChange={e=>update(selected!.kind,selectedItem.id,{height:Number(e.target.value)})}/></label><label>Rotation<input type="number" step="15" value={Math.round(selectedItem.rotation)} onChange={e=>update(selected!.kind,selectedItem.id,{rotation:Number(e.target.value)})}/></label>{selected?.kind==="object"&&<><label>Layer<input type="number" value={selectedItem.z_index||0} onChange={e=>update("object",selectedItem.id,{z_index:Number(e.target.value)})}/></label><div className="layout-object-actions"><button onClick={saveObjectDetails}>Save details</button><button onClick={duplicateObject}>Duplicate</button><button className="danger-button" onClick={removeObject}>Remove</button></div></>}</>}</aside></div>
 </section></main>}
