"use client";
import { FormEvent,useEffect,useMemo,useState } from "react";
type Status="free"|"contains"|"may_contain";
type Item={id:number;name:string;category:string;description:string|null;ingredients:string|null;milk_status:Status;nuts_status:Status;egg_status:Status;gluten_status:Status;vegetarian:number;can_make_vegetarian:number;vegetarian_changes:string|null;can_make_gluten_free:number;gluten_free_changes:string|null;active:number};
type Filters={milkFree:boolean;nutFree:boolean;eggFree:boolean;glutenFree:boolean;vegetarian:boolean;canMakeVegetarian:boolean};
const emptyFilters:Filters={milkFree:false,nutFree:false,eggFree:false,glutenFree:false,vegetarian:false,canMakeVegetarian:false};
const blank:Partial<Item>={name:"",category:"Main meals",milk_status:"free",nuts_status:"free",egg_status:"free",gluten_status:"free",vegetarian:0,can_make_vegetarian:0,can_make_gluten_free:0,active:1};
function statusLabel(status:Status,allergen:string){return status==="free"?`${allergen} free`:status==="contains"?`Contains ${allergen}`:`May contain ${allergen}`}
export default function BookingAllergenPage(){const [items,setItems]=useState<Item[]>([]),[manager,setManager]=useState(false),[query,setQuery]=useState(""),[category,setCategory]=useState(""),[filters,setFilters]=useState<Filters>(emptyFilters),[editing,setEditing]=useState<Partial<Item>|null>(null),[showInactive,setShowInactive]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(""),[notice,setNotice]=useState("");
 async function load(){try{const r=await fetch("/api/booking/allergens",{credentials:"include"});if(!r.ok)throw new Error();const data=await r.json();setItems(data.items);setManager(data.manager);setError("")}catch{setError("The allergen menu could not be loaded.")}finally{setLoading(false)}}
 useEffect(()=>{let active=true;fetch("/api/booking/allergens",{credentials:"include"}).then(r=>{if(!r.ok)throw new Error();return r.json()}).then(data=>{if(active){setItems(data.items);setManager(data.manager)}}).catch(()=>{if(active)setError("The allergen menu could not be loaded.")}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[]);
 const categories=useMemo(()=>[...new Set(items.map(item=>item.category))],[items]);const visible=useMemo(()=>items.filter(item=>{const term=query.trim().toLowerCase();return(showInactive||Boolean(item.active))&&(!category||item.category===category)&&(!term||item.name.toLowerCase().includes(term)||(item.ingredients||"").toLowerCase().includes(term))&&(!filters.milkFree||item.milk_status==="free")&&(!filters.nutFree||item.nuts_status==="free")&&(!filters.eggFree||item.egg_status==="free")&&(!filters.glutenFree||item.gluten_status==="free"||Boolean(item.can_make_gluten_free))&&(!filters.vegetarian||Boolean(item.vegetarian))&&(!filters.canMakeVegetarian||Boolean(item.vegetarian)||Boolean(item.can_make_vegetarian))}),[items,query,category,filters,showInactive]);
 async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget),payload={name:data.get("name"),category:data.get("category"),description:data.get("description"),ingredients:data.get("ingredients"),milkStatus:data.get("milkStatus"),nutsStatus:data.get("nutsStatus"),eggStatus:data.get("eggStatus"),glutenStatus:data.get("glutenStatus"),vegetarian:data.get("vegetarian")==="on",canMakeVegetarian:data.get("canMakeVegetarian")==="on",vegetarianChanges:data.get("vegetarianChanges"),canMakeGlutenFree:data.get("canMakeGlutenFree")==="on",glutenFreeChanges:data.get("glutenFreeChanges"),active:data.get("active")==="on"};const r=await fetch(editing?.id?`/api/booking/allergens/${editing.id}`:"/api/booking/allergens",{method:editing?.id?"PUT":"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}),result=await r.json().catch(()=>({}));if(!r.ok){setError(result.detail||"The menu item could not be saved.");return}setEditing(null);setNotice(editing?.id?"Menu item updated.":"Menu item added.");await load()}
 function toggle(name:keyof Filters){setFilters(current=>({...current,[name]:!current[name]}))}
 const statusOptions=<><option value="free">Free</option><option value="contains">Contains</option><option value="may_contain">May contain</option></>;
 return <main className="booking-main"><section className="booking-page"><header className="booking-heading"><div><span className="booking-page-kicker">Booking Portal</span><h1>Allergen Menu</h1><p>Search the menu and keep allergen information up to date.</p></div>{manager&&<button className="primary-button" onClick={()=>setEditing(blank)}>Add menu item</button>}</header><aside className="allergen-staff-warning"><strong>Always confirm allergies with the customer.</strong><span>Ingredients and suppliers can change. Check the latest kitchen information before confirming an order.</span></aside>
 <div className="booking-allergen-filters"><div className="booking-search"><input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search meal or ingredient"/><select value={category} onChange={e=>setCategory(e.target.value)}><option value="">All categories</option>{categories.map(value=><option key={value}>{value}</option>)}</select></div><div className="booking-filter-heading"><strong>Only show meals suitable for:</strong><button onClick={()=>{setFilters(emptyFilters);setQuery("");setCategory("")}}>Clear filters</button></div><div className="booking-filter-grid">{([['milkFree','Milk free'],['nutFree','Nuts free'],['eggFree','Egg free'],['glutenFree','Gluten free / adaptable'],['vegetarian','Vegetarian'],['canMakeVegetarian','Vegetarian / adaptable']] as [keyof Filters,string][]).map(([name,text])=><label key={name}><input type="checkbox" checked={filters[name]} onChange={()=>toggle(name)}/><span>{text}</span></label>)}{manager&&<label><input type="checkbox" checked={showInactive} onChange={e=>setShowInactive(e.target.checked)}/><span>Show inactive items</span></label>}</div></div>{error&&<p className="booking-alert">{error}</p>}{notice&&<p className="booking-notice">{notice}</p>}{loading?<div className="booking-empty">Loading allergen menu...</div>:<div className="staff-allergen-grid">{visible.map(item=><article className={`staff-allergen-card ${item.active?"":"is-inactive"}`} key={item.id}><span className="booking-page-kicker">{item.category}{item.active?"":" · Inactive"}</span><h2>{item.name}</h2><div className="staff-allergen-badges">{([[item.milk_status,'Milk'],[item.nuts_status,'Nuts'],[item.egg_status,'Egg'],[item.gluten_status,'Gluten']] as [Status,string][]).map(([value,name])=><span className={`allergen-${value}`} key={name}>{statusLabel(value,name)}</span>)}</div><div className="staff-diet-row">{Boolean(item.vegetarian)&&<span>Vegetarian</span>}{!item.vegetarian&&Boolean(item.can_make_vegetarian)&&<span>Can be vegetarian</span>}{Boolean(item.can_make_gluten_free)&&<span>Can be gluten free</span>}</div>{item.ingredients&&<details><summary>Ingredients</summary><p>{item.ingredients.split("\n").filter(Boolean).join(", ")}</p></details>}{manager&&<button onClick={()=>setEditing(item)}>Edit item</button>}</article>)}</div>}{!loading&&visible.length===0&&<div className="booking-empty">No matching menu items.</div>}
 {editing&&<div className="booking-modal-backdrop"><form className="booking-modal" onSubmit={save}><div className="booking-modal-heading"><h2>{editing.id?"Edit menu item":"Add menu item"}</h2><button type="button" onClick={()=>setEditing(null)}>×</button></div><div className="booking-form-grid"><label>Name<input name="name" defaultValue={editing.name||""} required/></label><label>Category<input name="category" defaultValue={editing.category||""} required/></label><label>Milk<select name="milkStatus" defaultValue={editing.milk_status}>{statusOptions}</select></label><label>Nuts<select name="nutsStatus" defaultValue={editing.nuts_status}>{statusOptions}</select></label><label>Egg<select name="eggStatus" defaultValue={editing.egg_status}>{statusOptions}</select></label><label>Gluten<select name="glutenStatus" defaultValue={editing.gluten_status}>{statusOptions}</select></label><label className="booking-check"><input name="vegetarian" type="checkbox" defaultChecked={Boolean(editing.vegetarian)}/> Vegetarian</label><label className="booking-check"><input name="canMakeVegetarian" type="checkbox" defaultChecked={Boolean(editing.can_make_vegetarian)}/> Can be made vegetarian</label><label className="booking-check"><input name="canMakeGlutenFree" type="checkbox" defaultChecked={Boolean(editing.can_make_gluten_free)}/> Can be made gluten free</label><label className="booking-check"><input name="active" type="checkbox" defaultChecked={editing.active!==0}/> Active</label><label className="booking-form-wide">Ingredients<textarea name="ingredients" rows={4} defaultValue={editing.ingredients||""}/></label><label className="booking-form-wide">Vegetarian changes<textarea name="vegetarianChanges" rows={2} defaultValue={editing.vegetarian_changes||""}/></label><label className="booking-form-wide">Gluten-free changes<textarea name="glutenFreeChanges" rows={2} defaultValue={editing.gluten_free_changes||""}/></label></div><div className="booking-modal-actions"><button type="button" onClick={()=>setEditing(null)}>Cancel</button><button className="primary-button">Save item</button></div></form></div>}
 </section></main>}
