"use client";
import Link from "next/link";
import { FormEvent,useCallback,useEffect,useState } from "react";
type Table={id:number;number:string;capacity:number;area_id:number;area:string;near_tv:number;has_bench:number;accessible:number;unsuitable_for_food:number;active:number};type Area={id:number;name:string};type Pairing={id:number;table_a_id:number;table_b_id:number;table_a_number:string;table_b_number:string;combined_capacity:number};
export default function TablesPage(){const [tables,setTables]=useState<Table[]>([]),[areas,setAreas]=useState<Area[]>([]),[pairings,setPairings]=useState<Pairing[]>([]),[editing,setEditing]=useState<Partial<Table>|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const load=useCallback(async()=>{try{const r=await fetch("/api/booking/tables",{credentials:"include"});if(!r.ok)throw new Error();const data=await r.json();setTables(data.tables);setAreas(data.areas);setPairings(data.pairings);setError("")}catch{setError("Tables could not be loaded. Manager access is required.")}finally{setLoading(false)}},[]);useEffect(()=>{let active=true;fetch("/api/booking/tables",{credentials:"include"}).then(r=>{if(!r.ok)throw new Error();return r.json()}).then(data=>{if(active){setTables(data.tables);setAreas(data.areas);setPairings(data.pairings)}}).catch(()=>{if(active)setError("Tables could not be loaded. Manager access is required.")}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[]);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget),payload={number:d.get("number"),capacity:Number(d.get("capacity")),areaId:Number(d.get("areaId")),nearTv:d.get("nearTv")==="on",hasBench:d.get("hasBench")==="on",accessible:d.get("accessible")==="on",unsuitableForFood:d.get("unsuitableForFood")==="on",active:editing?.id?d.get("active")==="on":true};const r=await fetch(editing?.id?`/api/booking/tables/${editing.id}`:"/api/booking/tables",{method:editing?.id?"PUT":"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}),result=await r.json().catch(()=>({}));if(!r.ok){setError(result.detail||result.message||"The table could not be saved.");return}setEditing(null);setNotice(editing?.id?"Table updated.":"Table added.");await load()}
 async function pair(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget),r=await fetch("/api/booking/tables/pairings",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({tableAId:Number(d.get("tableAId")),tableBId:Number(d.get("tableBId"))})}),result=await r.json().catch(()=>({}));if(!r.ok){setError(result.detail||result.message||"The pairing could not be created.");return}e.currentTarget.reset();setNotice("Table pairing added.");await load()}
 async function unpair(id:number){if(!confirm("Remove this table pairing?"))return;const r=await fetch(`/api/booking/tables/pairings/${id}`,{method:"DELETE",credentials:"include"});if(!r.ok){setError("The pairing could not be removed.");return}setNotice("Table pairing removed.");await load()}
 return <main className="booking-main"><section className="booking-page"><header className="booking-heading"><div><span className="booking-page-kicker">Manager tools</span><h1>Tables</h1><p>Configure capacities, areas, characteristics and table pairings.</p></div><div className="booking-heading-actions"><Link href="/booking/table-layout">Layout editor</Link><button className="primary-button" onClick={()=>setEditing({capacity:2,active:1})}>Add table</button></div></header>{error&&<p className="booking-alert">{error}</p>}{notice&&<p className="booking-notice">{notice}</p>}
 {loading?<div className="booking-empty">Loading tables...</div>:<><div className="table-management-grid">{tables.map(table=><article className={`managed-table-card ${table.active?"":"inactive"}`} key={table.id}><div><strong>T{table.number}</strong><button onClick={()=>setEditing(table)}>Edit</button></div><h2>{table.capacity} seats</h2><p>{table.area}</p><div className="table-feature-tags">{table.near_tv? <span>Near TV</span>:null}{table.has_bench?<span>Bench</span>:null}{table.accessible?<span>Accessible</span>:null}{table.unsuitable_for_food?<span className="warning">Food last resort</span>:null}{!table.active?<span className="inactive-tag">Inactive</span>:null}</div></article>)}</div>
 <section className="table-pairing-panel"><div><h2>Table pairings</h2><p>Define tables that can physically be pushed together.</p></div><form onSubmit={pair}><select name="tableAId" required defaultValue=""><option value="">First table</option>{tables.filter(t=>t.active).map(t=><option key={t.id} value={t.id}>Table {t.number}</option>)}</select><span>+</span><select name="tableBId" required defaultValue=""><option value="">Second table</option>{tables.filter(t=>t.active).map(t=><option key={t.id} value={t.id}>Table {t.number}</option>)}</select><button>Create pairing</button></form><div className="pairing-tags">{pairings.map(p=><span key={p.id}>T{p.table_a_number} + T{p.table_b_number} = {p.combined_capacity} seats <button aria-label="Remove pairing" onClick={()=>unpair(p.id)}>×</button></span>)}</div></section></>}
 {editing&&<div className="booking-modal-backdrop"><form className="booking-modal" onSubmit={save}><div className="booking-modal-heading"><h2>{editing.id?`Edit table ${editing.number}`:"Add table"}</h2><button type="button" onClick={()=>setEditing(null)}>×</button></div><div className="booking-form-grid"><label>Table number<input name="number" defaultValue={editing.number||""} required/></label><label>Capacity<input name="capacity" type="number" min="1" defaultValue={editing.capacity||2} required/></label><label>Area<select name="areaId" defaultValue={editing.area_id||""} required><option value="">Choose area</option>{areas.map(a=><option value={a.id} key={a.id}>{a.name}</option>)}</select></label><label className="booking-check"><input name="nearTv" type="checkbox" defaultChecked={Boolean(editing.near_tv)}/> Near a TV</label><label className="booking-check"><input name="hasBench" type="checkbox" defaultChecked={Boolean(editing.has_bench)}/> Bench seating</label><label className="booking-check"><input name="accessible" type="checkbox" defaultChecked={Boolean(editing.accessible)}/> Accessible</label><label className="booking-check"><input name="unsuitableForFood" type="checkbox" defaultChecked={Boolean(editing.unsuitable_for_food)}/> Food last resort</label>{editing.id&&<label className="booking-check"><input name="active" type="checkbox" defaultChecked={Boolean(editing.active)}/> Active for bookings</label>}</div><div className="booking-modal-actions"><button type="button" onClick={()=>setEditing(null)}>Cancel</button><button className="primary-button">Save table</button></div></form></div>}
 </section></main>}
